"""GitSyncHook: automatic git pull/commit lifecycle around agent runs.

Runs git pull --rebase before the first iteration and commits all changes
after the final iteration (when stop_reason is set).

Commit messages are generated by a lightweight LLM call (Haiku by default)
using git diff and recent trace events as context.

Usage::

    loop = AgentLoop(..., hooks=[GitSyncHook(provider, workspace=workspace)])
"""

from __future__ import annotations

import asyncio
import json
import re
from datetime import datetime
from pathlib import Path
from typing import TYPE_CHECKING

from loguru import logger

from nanobot.agent.hook import AgentHook, AgentHookContext

if TYPE_CHECKING:
    from nanobot.providers.base import LLMProvider

# Shared across all GitSyncHook instances — prevents concurrent git index corruption.
_GIT_LOCK = asyncio.Lock()

_WRITE_TOOLS = frozenset({"write_file", "edit_file"})


class GitSyncHook(AgentHook):
    """Lifecycle hook that wraps every agent run with git pull + commit.

    The commit message is generated by a small LLM call with two inputs:
      1. ``git diff HEAD --stat`` + ``git status --short`` — what changed
      2. Recent ``tool_call`` events from the run's trace file — what the agent did

    If the LLM call fails for any reason, a structured fallback message is used.
    All git failures are logged and swallowed — this hook must never break a run.

    Args:
        provider: The same LLMProvider used by the agent loop.
        workspace: Workspace directory for git operations.
        model: Model for commit message generation. Defaults to Haiku (fast/cheap).
        remote: Git remote to pull from. Defaults to "origin".
        branch: Branch to rebase onto. Defaults to "main".
    """

    _DEFAULT_MODEL = "claude-haiku-4-5-20251001"
    _MAX_DIFF_CHARS = 3_000
    _MAX_TRACE_TOOL_CALLS = 20
    _MAX_COMMIT_TOKENS = 256

    def __init__(
        self,
        provider: LLMProvider,
        workspace: Path,
        model: str | None = None,
        remote: str = "origin",
        branch: str = "main",
        pull: bool = True,
    ) -> None:
        self._provider = provider
        self._workspace = workspace
        self._model = model or self._DEFAULT_MODEL
        self._remote = remote
        self._branch = branch
        self._pull = pull
        self._touched_files: set[str] = set()

    async def before_iteration(self, context: AgentHookContext) -> None:
        """Pull latest changes before the agent starts work (first iteration only)."""
        if not self._pull or context.iteration != 0:
            return
        try:
            rc, stderr = await _git(
                ["git", "pull", "--rebase", self._remote, self._branch],
                self._workspace,
            )
            if rc != 0:
                logger.warning("git pull failed (rc={}): {}", rc, stderr)
        except Exception as exc:
            logger.warning("GitSyncHook.before_iteration pull: {}", exc)

    async def before_execute_tools(self, context: AgentHookContext) -> None:
        """Track files written by this session."""
        for tc in context.tool_calls:
            if tc.name in _WRITE_TOOLS and "path" in tc.arguments:
                self._touched_files.add(tc.arguments["path"])

    async def after_iteration(self, context: AgentHookContext) -> None:
        """Commit only session-touched files after the agent finishes (final iteration only)."""
        if context.stop_reason is None:
            return
        files = list(self._touched_files)
        self._touched_files.clear()
        if not files:
            return
        try:
            trigger = "cron" if context.channel == "cron" else "channel"
            diff_summary = await _diff_summary(self._workspace, self._MAX_DIFF_CHARS)
            trace_context = _read_trace_tools(
                self._workspace, context.channel, context.chat_id, self._MAX_TRACE_TOOL_CALLS
            )
            commit_msg = await self._generate_commit_msg(
                trigger, context.stop_reason, diff_summary, trace_context
            )
            async with _GIT_LOCK:
                await _git(["git", "add"] + files, self._workspace)
                rc, stderr = await _git(["git", "commit", "-m", commit_msg], self._workspace)
            if rc != 0:
                logger.warning("git commit failed (rc={}): {}", rc, stderr)
        except Exception as exc:
            logger.warning("GitSyncHook.after_iteration commit: {}", exc)

    async def _generate_commit_msg(
        self,
        trigger: str,
        stop_reason: str,
        diff_summary: str,
        trace_context: str,
    ) -> str:
        """Ask the LLM to write a structured commit message."""
        tools_section = (
            f"\nTools used during run:\n{trace_context}" if trace_context else ""
        )
        prompt = (
            f"You summarize agent runs into git commit messages.\n"
            f"Write ONLY the commit message — no preamble, no markdown fences.\n\n"
            f"Trigger: {trigger}\n"
            f"Stop reason: {stop_reason}"
            f"{tools_section}\n\n"
            f"Workspace changes:\n{diff_summary}\n\n"
            f"Format (follow exactly):\n"
            f"[agent/{trigger}] <phase>: <one-line summary>\n\n"
            f"Status: <complete|ready-for-review|blocked>\n"
            f"Uncertainty: <what was unclear, or 'none'>"
            f"General summary: <what happened in the run>"
        )
        try:
            response = await self._provider.chat(
                messages=[{"role": "user", "content": prompt}],
                model=self._model,
                max_tokens=self._MAX_COMMIT_TOKENS,
                temperature=0.3,
            )
            msg = (response.content or "").strip()
            if msg:
                return msg
        except Exception as exc:
            logger.warning("GitSyncHook: commit message LLM call failed: {}", exc)

        return (
            f"[agent/{trigger}] auto: run complete\n\n"
            f"Status: {stop_reason}\n"
            f"Uncertainty: none"
        )


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


async def _git(cmd: list[str], cwd: Path) -> tuple[int, str]:
    """Run a git command, returning (returncode, stderr)."""
    proc = await asyncio.create_subprocess_exec(
        *cmd,
        cwd=cwd,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
    )
    _, stderr_bytes = await proc.communicate()
    return proc.returncode or 0, stderr_bytes.decode()


async def _diff_summary(workspace: Path, max_chars: int) -> str:
    """Return a short textual summary of uncommitted changes."""
    _, stat_out = await _git_stdout(["git", "diff", "HEAD", "--stat"], workspace)
    _, status_out = await _git_stdout(["git", "status", "--short"], workspace)
    combined = f"Status:\n{status_out}\nDiff stat:\n{stat_out}"
    return combined[:max_chars]


async def _git_stdout(cmd: list[str], cwd: Path) -> tuple[int, str]:
    proc = await asyncio.create_subprocess_exec(
        *cmd,
        cwd=cwd,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.DEVNULL,
    )
    stdout_bytes, _ = await proc.communicate()
    return proc.returncode or 0, stdout_bytes.decode()


def _read_trace_tools(workspace: Path, channel: str, chat_id: str, limit: int) -> str:
    """Read recent tool_call events from today's trace file for this session."""
    try:
        session_id = re.sub(r"[^a-zA-Z0-9_\-]", "_", f"{channel}:{chat_id}")
        date_str = datetime.now().strftime("%Y-%m-%d")
        trace_path = workspace / ".traces" / f"{session_id}_{date_str}.jsonl"
        if not trace_path.exists():
            return ""
        lines = trace_path.read_text(encoding="utf-8").strip().splitlines()
        calls: list[str] = []
        for line in lines:
            try:
                rec = json.loads(line)
                if rec.get("event") == "tool_call":
                    preview = rec.get("args_preview", "")[:60]
                    calls.append(f"- {rec['tool']}({preview})")
            except Exception:
                pass
        return "\n".join(calls[-limit:])
    except Exception:
        return ""
