from typing import Protocol
from uuid import UUID


class IUserRepo(Protocol):
    async def create(self, email: str) -> dict: ...
    async def find_by_id(self, user_id: UUID) -> dict | None: ...
    async def find_by_email(self, email: str) -> dict | None: ...
    async def set_token(self, user_id: UUID, token: str) -> None: ...
    async def find_by_token(self, token: str) -> dict | None: ...
