"""Secondary (outbound) ports — interfaces the app layer needs from infrastructure."""
from typing import Protocol
from uuid import UUID


class IWorkspaceRepo(Protocol):
    async def create(self, user_id: UUID, name: str, token: str) -> dict: ...
    async def find_by_id(self, workspace_id: UUID) -> dict | None: ...
    async def find_by_token(self, token: str) -> dict | None: ...
    async def list_by_user(self, user_id: UUID) -> list[dict]: ...
