from typing import Protocol
from uuid import UUID

import asyncpg


class IEnvRepo(Protocol):
    async def create(self, user_id: UUID, name: str, values: dict, category: str | None = None) -> asyncpg.Record: ...
    async def find_by_id(self, env_id: UUID) -> asyncpg.Record | None: ...
    async def list_by_user(self, user_id: UUID) -> list[asyncpg.Record]: ...
    async def find_llm_provider_by_user(self, user_id: UUID) -> asyncpg.Record | None: ...
    async def get_decrypted_values(self, env_id: UUID) -> dict: ...
    async def update(self, env_id: UUID, name: str | None = None, values: dict | None = None, category: str | None = None) -> asyncpg.Record | None: ...
    async def delete(self, env_id: UUID) -> None: ...


class IChannelRepo(Protocol):
    async def create(self, user_id: UUID, type_: str, config: dict) -> asyncpg.Record: ...
    async def find_by_id(self, channel_id: UUID) -> asyncpg.Record | None: ...
    async def list_by_user(self, user_id: UUID) -> list[asyncpg.Record]: ...
    async def get_decrypted_config(self, channel_id: UUID) -> dict: ...
    async def delete(self, channel_id: UUID) -> None: ...


class IUserMcpRepo(Protocol):
    async def create(self, user_id: UUID, name: str, type_: str, config: dict) -> asyncpg.Record: ...
    async def find_by_id(self, mcp_id: UUID) -> asyncpg.Record | None: ...
    async def list_by_user(self, user_id: UUID) -> list[asyncpg.Record]: ...
    async def get_decrypted_config(self, mcp_id: UUID) -> dict: ...
    async def delete(self, mcp_id: UUID) -> None: ...


class IUserTemplateRepo(Protocol):
    async def create(self, user_id: UUID, name: str, template_type: str, content: str) -> asyncpg.Record: ...
    async def find_by_id(self, template_id: UUID) -> asyncpg.Record | None: ...
    async def list_by_user(self, user_id: UUID) -> list[asyncpg.Record]: ...
    async def update(self, template_id: UUID, name: str | None = None, content: str | None = None) -> asyncpg.Record | None: ...
    async def delete(self, template_id: UUID) -> None: ...


class ISkillLinkRepo(Protocol):
    async def attach(self, agent_id: UUID, skill_id: UUID) -> None: ...
    async def detach(self, agent_id: UUID, skill_id: UUID) -> None: ...
    async def list_by_agent(self, agent_id: UUID) -> list[asyncpg.Record]: ...


class IEnvLinkRepo(Protocol):
    async def attach(self, agent_id: UUID, env_id: UUID) -> None: ...
    async def detach(self, agent_id: UUID, env_id: UUID) -> None: ...
    async def list_by_agent(self, agent_id: UUID) -> list[asyncpg.Record]: ...


class IChannelLinkRepo(Protocol):
    async def attach(self, agent_id: UUID, channel_id: UUID) -> None: ...
    async def detach(self, agent_id: UUID, channel_id: UUID) -> None: ...
    async def list_by_agent(self, agent_id: UUID) -> list[asyncpg.Record]: ...


class IMcpLinkRepo(Protocol):
    async def attach(self, agent_id: UUID, mcp_id: UUID) -> None: ...
    async def detach(self, agent_id: UUID, mcp_id: UUID) -> None: ...
    async def list_by_agent(self, agent_id: UUID) -> list[asyncpg.Record]: ...
    async def list_decrypted(self, agent_id: UUID) -> list[dict]: ...


class ITemplateLinkRepo(Protocol):
    async def attach(self, agent_id: UUID, template_id: UUID, template_type: str) -> None: ...
    async def detach(self, agent_id: UUID, template_id: UUID) -> None: ...
    async def list_by_agent(self, agent_id: UUID) -> list[asyncpg.Record]: ...
