from typing import Protocol
from uuid import UUID


class IEnvRepo(Protocol):
    async def create(self, user_id: UUID, name: str, values: dict) -> dict: ...
    async def find_by_id(self, env_id: UUID) -> dict | None: ...
    async def list_by_user(self, user_id: UUID) -> list[dict]: ...
    async def get_decrypted_config(self, env_id: UUID) -> dict: ...
    async def delete(self, env_id: UUID) -> None: ...


class IChannelRepo(Protocol):
    async def create(self, user_id: UUID, channel_type: str, config: dict) -> dict: ...
    async def find_by_id(self, channel_id: UUID) -> dict | None: ...
    async def list_by_user(self, user_id: UUID) -> list[dict]: ...
    async def delete(self, channel_id: UUID) -> None: ...


class ILinkRepo(Protocol):
    async def attach_skill(self, agent_id: UUID, skill_id: UUID) -> None: ...
    async def detach_skill(self, agent_id: UUID, skill_id: UUID) -> None: ...
    async def list_skills(self, agent_id: UUID) -> list[dict]: ...
    async def attach_env(self, agent_id: UUID, env_id: UUID) -> None: ...
    async def detach_env(self, agent_id: UUID, env_id: UUID) -> None: ...
    async def list_envs(self, agent_id: UUID) -> list[dict]: ...
    async def attach_channel(self, agent_id: UUID, channel_id: UUID) -> None: ...
    async def detach_channel(self, agent_id: UUID, channel_id: UUID) -> None: ...
    async def list_channels(self, agent_id: UUID) -> list[dict]: ...


class IAgentMcpRepo(Protocol):
    async def add(self, agent_id: UUID, name: str, config: dict) -> dict: ...
    async def list_by_agent(self, agent_id: UUID) -> list[dict]: ...
    async def get_decrypted_config(self, mcp_id: UUID) -> dict: ...
