from typing import Protocol
from uuid import UUID


class IAgentRepo(Protocol):
    async def create(
        self, user_id: UUID, name: str, image: str, is_admin: bool
    ) -> dict: ...
    async def find_by_id(self, agent_id: UUID) -> dict | None: ...
    async def list_by_user(self, user_id: UUID) -> list[dict]: ...
    async def list_running(self) -> list[dict]: ...
    async def update(self, agent_id: UUID, **kwargs) -> dict | None: ...
    async def delete(self, agent_id: UUID) -> None: ...


class IAgentFileRepo(Protocol):
    async def upsert(self, agent_id: UUID, path: str, content: str) -> dict: ...
    async def find(self, agent_id: UUID, path: str) -> dict | None: ...
    async def list_by_agent(self, agent_id: UUID) -> list[dict]: ...
    async def bulk_upsert(self, agent_id: UUID, files: list[dict]) -> None: ...
