from pathlib import Path
from typing import Protocol
from uuid import UUID


class ISandboxRunner(Protocol):
    """Out-port: sandbox lifecycle backend (Docker for dev, microsandbox for prod).

    Implementations own the runner-specific protocol (subprocess, Python SDK).
    SandboxService talks only to this interface — no runner-specific code in
    the app layer.
    """

    async def start(
        self,
        *,
        name: str,
        image: str,
        workdir: Path,
        gateway_port: int,
        env: dict[str, str],
    ) -> None: ...

    async def stop(self, name: str) -> None: ...

    async def remove(self, name: str) -> None: ...

    async def force_remove(self, name: str) -> None: ...

    async def is_alive(self, name: str) -> bool: ...

    async def capture_logs(self, name: str, tail: int = 80) -> str: ...


class IAgentRepo(Protocol):
    async def create(
        self, workspace_id: UUID, name: str, image: str, is_admin: bool
    ) -> dict: ...
    async def find_by_id(self, agent_id: UUID) -> dict | None: ...
    async def list_by_workspace(self, workspace_id: UUID) -> list[dict]: ...
    async def list_running(self) -> list[dict]: ...
    async def update(self, agent_id: UUID, **kwargs) -> dict | None: ...
    async def delete(self, agent_id: UUID) -> None: ...


class IAgentFileRepo(Protocol):
    async def upsert(self, agent_id: UUID, path: str, content: str) -> dict: ...
    async def find(self, agent_id: UUID, path: str) -> dict | None: ...
    async def list_by_agent(self, agent_id: UUID) -> list[dict]: ...
    async def bulk_upsert(self, agent_id: UUID, files: list[dict]) -> None: ...
