"""Inbound port — what the app layer offers to in-adapters."""
from typing import Protocol
from uuid import UUID


class IKnowledgeApp(Protocol):
    async def ingest(self, workspace_id: UUID, text: str, metadata: dict) -> None: ...
    async def ingest_file(self, workspace_id: UUID, content: bytes, content_type: str, filename: str) -> None: ...
    async def query(self, workspace_id: UUID, query: str, mode: str) -> str: ...
    async def get_graph(self, workspace_id: UUID) -> dict: ...
