"""Outbound ports — what the app layer requires from external dependencies."""
from typing import Protocol
from uuid import UUID


class IKnowledgeStore(Protocol):
    async def ingest(self, user_id: UUID, text: str, metadata: dict) -> None: ...
    async def query(self, user_id: UUID, query: str, mode: str) -> str: ...
    async def get_graph(self, user_id: UUID) -> dict: ...


class IDocumentNormalizer(Protocol):
    """Converts raw file bytes into plain text suitable for LightRAG ingestion."""

    async def normalize(self, content: bytes, content_type: str, filename: str) -> str: ...
    def supported_types(self) -> frozenset[str]: ...
