from typing import Protocol


class StoragePort(Protocol):
    async def put_object(self, key: str, data: bytes, content_type: str) -> None: ...
    async def delete_object(self, key: str) -> None: ...
    def public_url(self, key: str) -> str: ...
